
#pragma once

#include <stdint.h>

#define _GPIO_PIN_SET(PORT,PIN) PORT##_set( 1<<PIN )
#define _GPIO_PIN_CLR(PORT,PIN) PORT##_clr( 1<<PIN )
#define _GPIO_PIN_WRITE(PORT,PIN,VALUE) do { if(VALUE) PORT##_set(1<<PIN); else PORT##_clr(1<<PIN); } while(0)
#define _GPIO_PIN_READ(PORT,PIN) ((PORT##_read() >> PIN) & 0x1)

#define GPIO_PIN_SET(PORT,PIN) _GPIO_PIN_SET(PORTPIN,VALUE)
#define GPIO_PIN_CLR(PORT,PIN) _GPIO_PIN_CLR(PORTPIN,VALUE)
#define GPIO_PIN_WRITE(PORTPIN,VALUE) _GPIO_PIN_WRITE(PORTPIN,VALUE)
#define GPIO_PIN_READ (PORTPIN,VALUE) _GPIO_PIN_READ (PORTPIN,VALUE)
