
#pragma once

#define _TIMER_COUNTER(TIMER) TIMER##_counter()
#define _TIMER_SET_COUNTER(TIMER,VALUE) TIMER##_set_counter(value)

#define _TIMER_HAS_OVERFLOW(TIMER) TIMER##_has_overflow()
#define _TIMER_CLEAR_OVERFLOW(TIMER) TIMER##_clear_overflow()

#define TIMER_COUNTER(TIMER) _TIMER_COUNTER(TIMER)
#define TIMER_SET_COUNTER(TIMER,VALUE) _TIMER_SET_COUNTER(TIMER,VALUE)

#define TIMER_HAS_OVERFLOW(TIMER) _TIMER_HAS_OVERFLOW(TIMER)
#define TIMER_CLEAR_OVERFLOW(TIMER) _TIMER_CLEAR_OVERFLOW(TIMER)

